server:
  port: 8889

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/ridoh/Downloads/HealthConnect-Microservice/healthconnect-config-repo
          default-label: main
          force-pull: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.config: DEBUG
